[can.private_use]
protect_scope = ["source_code", "binary_from", "derivative_work",]
escape_scope = []

[can.commercial_use]
protect_scope = ["source_code", "binary_from", "derivative_work",]
escape_scope = []

[can.distribute]
protect_scope = ["source_code", "binary_from", "derivative_work",]
escape_scope = []

[can.modify]
protect_scope = ["source_code", "binary_from", "derivative_work",]
escape_scope = []

[can.patent_grant]
protect_scope = []
escape_scope = []

[must.include_copyright]
protect_scope = []
escape_scope = ["derivative_work"]

[must.include_license]
protect_scope = ["source_code", "binary_from", "derivative_work",]
escape_scope = []

[must.include_notice]
protect_scope = []
escape_scope = ["derivative_work"]

[must.state_changes]
protect_scope = []
escape_scope = []

[cannot.patent_suit]
protect_scope = []
escape_scope = []

[cannot.provide_warranty]
protect_scope = []
escape_scope = []

[cannot.use_trademark]
protect_scope = ["trademark"]
escape_scope = []
