human_review = false

[must]

[can.commercial_use]
protect_scope = []
escape_scope = []

[can.private_use]
protect_scope = []
escape_scope = []

[can.modify]
protect_scope = []
escape_scope = []

[can.distribute]
protect_scope = []
escape_scope = []

[cannot.use_trademark]
protect_scope = ["trademark"]
escape_scope = []

[cannot.provide_warranty]
protect_scope = []
escape_scope = []

# golden example ?
[cannot.patent_grant]
protect_scope = []
escape_scope = []
