human_review = false

[can.commercial_use]
protect_scope = []
escape_scope = []

[can.private_use]
protect_scope = []
escape_scope = []

[can.modify]
protect_scope = []
escape_scope = []

[can.distribute]
protect_scope = []
escape_scope = []

[cannot.use_trademark]
protect_scope = [ "TRADEMARK",]
escape_scope = []

[cannot.provide_warranty]
protect_scope = []
escape_scope = []

[cannot.patent_grant]
protect_scope = []
escape_scope = []
