[license_spread]
spread_conditions = ["STATIC_LINKING", "COMPILE"]
non_spread_conditions = ["DEFAULT", "DYNAMIC_LINKING"]

[literal_mapping]
code = "COMPILE"
shared_library = "DYNAMIC_LINKING"
static_library = "STATIC_LINKING"
